### ISSUE TITLE
Optimize contao-avatar for Contao 4.3+

### ISSUE THREAD

**Issue by iCodr8** [terminal42/contao-avatar#12]
The module has some problems with Contao 4.3.

For example:
`Invalid file or folder name app/../assets/images/d/xxx__12-08fd141f.png`
on
`vendor/terminal42/contao-avatar/forms/FormAvatar.php:109`

I'll hope this module can be made stable for contao 4.3

**Comment by aschempp** [comment]
Can you provide a pull request to fix the issues?

**Comment by iCodr8** [comment]
I habe no idea, how to solve this.

**Comment by qzminski** [comment]
Cannot reproduce on Contao 4.4 LTS and `develop` branch.
