### ISSUE TITLE
Image cut in frontend is defect

### ISSUE THREAD

**Issue by iCodr8** [terminal42/contao-avatar#13]
![screen shot 2017-04-02 at 22 22 10](https://cloud.githubusercontent.com/assets/1264033/24590754/280502e6-17f3-11e7-9efe-b2b0b96e9d07.png)

When I am cutting an image in the frontend and click on "cut" (German: "Zuschneiden") then I get the following error. The image was uploaded and saved to "system/tmp/..", but the image seems to be defect.

![screen shot 2017-04-02 at 22 22 15](https://cloud.githubusercontent.com/assets/1264033/24590752/21b9324a-17f3-11e7-9ac3-f004bf8bffac.png)

Contao 4.3.7

**Comment by qzminski** [comment]
Does it happen for other images as well or just that particular one? Maybe the image is corrupted indeed.

**Comment by qzminski** [comment]
I have just checked this on 4.4.7 LTS and it seems that it's working fine on `develop` branch ¯\_(ツ)_/¯.
