### ISSUE TITLE
No storage of an uploaded image in the BE, if you forgot the cut

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-avatar#16]
No storage of an uploaded image in the BE, if you forgot the cut

C 4.4
Avatar 1.3.0 (master and develop)

**Comment by fritzmg** [comment]
@zonky2 what exactly do you mean?

**Comment by zonky2** [comment]
if you don't crop the image, it won't be saved

**Comment by qzminski** [comment]
What do you actually mean by "forgot the cut"? When you upload an image you get to the cropping interface, where you can either crop (and save) the image or delete it.

<img width="244" alt="Zrzut ekranu 2020-02-18 o 15 06 33" src="https://user-images.githubusercontent.com/193483/74743180-423f3c80-5260-11ea-9210-1b01457eab9a.png">

This is a second step of the saving image process of this extension, so you gotta confirm (i.e. crop) your upload before it is actually saved to the database.

1. First step is to upload image.
2. Second step is to crop or delete the image.
3. Last step is to save the record.

**Comment by zonky2** [comment]
Use

1. First step: upload image.
2. Last step: save the record.

your crop is "mandatory", but not at all images necessary

**Comment by qzminski** [comment]
In such case you should select the "User - avatar auto-resize" checkbox in the system settings.

**Comment by zonky2** [comment]
Where can I find that there is such a setting? there is nothing about it in the readme :(

The setting should be default in my opinion.
