### ISSUE TITLE
File is too large, maximum file size is 500.0kB

### ISSUE THREAD

**Issue by Samson1964** [terminal42/contao-avatar#20]
Fehlermeldung beim Upload bei Mitgliedern im BE. Und das trotz Einstellung von 2 MB als Uploadgröße. 
Der Fehler ist in tl_member.php:
```php
'maxlength' => \Config::get('avatar_user_maxlength'), 
```
Das soll wohl eher heißen:
```php
'maxlength' => \Config::get('avatar_member_maxlength'), 
```

**Comment by qzminski** [comment]
Released in 1.3.2 :+1:
