### ISSUE TITLE
Avatar is not shown in the frontend

### ISSUE THREAD

**Issue by seibtph** [terminal42/contao-avatar#21]
The avatar is not shown in the frontend. The inserttags and the php code doesn't work.

Contao 4.9.2

The image will not saved in the assets folder assets/avatars/members. I don't know why...

**Comment by qzminski** [comment]
What is your extension version? Are there any error logs in the Contao backend or in the `var/logs` folder? Do you get any JS console error during avatar upload?

**Comment by tsarma** [comment]
May be this is related to https://github.com/terminal42/contao-avatar/pull/22

**Comment by qzminski** [comment]
@seibtph can you update extension to 1.3.3 and see if the problem still occurs?

**Comment by dp-designpilot** [comment]
Hello Kamil
When i update the extension to 1.3.3 looks the same problem like this #24. Can you fix this problem ?
