### ISSUE TITLE
Avatar is not shown in the backend and frontend

### ISSUE THREAD

**Issue by dp-designpilot** [terminal42/contao-avatar#24]
Hello Kamil
I have a Problem thats not shown the Avatar in the Backend at this Section:

User -> User Editing
![Bildschirmfoto 2020-07-17 um 23 56 15](https://user-images.githubusercontent.com/57160987/87833877-35fbf180-c889-11ea-8bf2-5bcb732c2ce5.png)

and when I save it, the file is deleted
![Bildschirmfoto 2020-07-18 um 00 14 18](https://user-images.githubusercontent.com/57160987/87834821-a7d53a80-c88b-11ea-8646-3f6029121d70.png)

I also checked the directory /var/logs if it created a log file but it did not create a log file

System -> Settings
![Bildschirmfoto 2020-07-17 um 23 54 03](https://user-images.githubusercontent.com/57160987/87834045-aefb4900-c889-11ea-9f8a-c791774aa4fc.png)

![Bildschirmfoto 2020-07-17 um 23 53 53](https://user-images.githubusercontent.com/57160987/87834053-b3bffd00-c889-11ea-9444-9f41dc852b15.png)

The avatars are shown here, but the directory on Server (root) /assets/avatars/members and /assets/avatars/users is then empty.

In the Frontend is not shown the Avatar

Can you Help me ??

**Comment by jscholtysik** [comment]
Same problem here.

- Contao 4.9.11
- PHP 7.2
- Contao Manager 1.4.0
- Composer 2.0

**Comment by dp-designpilot** [comment]
> Hello Kamil
> I have a Problem thats not shown the Avatar in the Backend at this Section:
> 
> User -> User Editing
> ![Bildschirmfoto 2020-07-17 um 23 56 15](https://user-images.githubusercontent.com/57160987/87833877-35fbf180-c889-11ea-8bf2-5bcb732c2ce5.png)
> 
> and when I save it, the file is deleted
> ![Bildschirmfoto 2020-07-18 um 00 14 18](https://user-images.githubusercontent.com/57160987/87834821-a7d53a80-c88b-11ea-8646-3f6029121d70.png)
> 
> I also checked the directory /var/logs if it created a log file but it did not create a log file
> 
> System -> Settings
> ![Bildschirmfoto 2020-07-17 um 23 54 03](https://user-images.githubusercontent.com/57160987/87834045-aefb4900-c889-11ea-9f8a-c791774aa4fc.png)
> 
> ![Bildschirmfoto 2020-07-17 um 23 53 53](https://user-images.githubusercontent.com/57160987/87834053-b3bffd00-c889-11ea-9444-9f41dc852b15.png)
> 
> The avatars are shown here, but the directory on Server (root) /assets/avatars/members and /assets/avatars/users is then empty.
> 
> In the Frontend is not shown the Avatar
> 
> Can you Help me ??

Hello Kamil

With the **hofix/1.3.3** the problem was not resolved it's still the same.

**Comment by aschempp** [comment]
I just tested this in my local setup and it seems to work perfectly fine. Be aware that you need to save the record in the back end for the data to be saved.
