### ISSUE TITLE
Editable Fields for FE-Users (Contao 3.4.5)

### ISSUE THREAD

**Issue by cgpro** [terminal42/contao-avatar#3]
I've included the extension within the module personal data for frontend-editing the personal data. For the avatar I've made a new content element with the module personal data and only the field avatar selected, but I get the following error in the frontend when I want to edit the Avatar as a logged in frontend member:
![bildschirmfoto 2015-08-12 um 04 25 19](https://cloud.githubusercontent.com/assets/1557147/9215387/45907ca4-40aa-11e5-9500-d204c05b5582.png)

Avatar
Fatal error: Uncaught exception BadMethodCallException with message Please use the parse() method instead! thrown in system/modules/avatar/forms/FormAvatar.php on line 202
#0 system/modules/core/library/Contao/Widget.php(685): FormAvatar->generate()
#1 _repos/vmi_frontend/templates/apr/form_avatar.html5(2): Contao\Widget->generateWithError()
#2 system/modules/core/library/Contao/BaseTemplate.php(88): include('/Applications/M...')
#3 system/modules/core/library/Contao/Widget.php(631): Contao\BaseTemplate->parse()
#4 system/modules/avatar/forms/FormAvatar.php(193): Contao\Widget->parse(NULL)
#5 system/modules/core/modules/ModulePersonalData.php(283): FormAvatar->parse()
#6 system/modules/core/modules/Module.php(154): Contao\ModulePersonalData->compile()
#7 system/modules/core/modules/ModulePersonalData.php(56): Contao\Module->generate()
#8 system/modules/core/elements/ContentModule.php(56): Contao\ModulePersonalData->generate()
#9 system/modules/core/library/Contao/Controller.php(469): Contao\ContentModule->generate()
#10 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#11 system/modules/core/modules/Module.php(154): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#13 system/modules/core/library/Contao/Controller.php(405): Contao\ModuleArticle->generate(false)
#14 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#15 system/modules/core/pages/PageRegular.php(129): Contao\Controller::getFrontendModule('0', 'main')
#16 system/modules/core/controllers/FrontendIndex.php(250): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#17 index.php(20): Contao\FrontendIndex->run()
#18 {main}

**Comment by cgpro** [comment]
Any news? We can support it financially if it helps!
(skype: cgpro83)

**Comment by Toflar** [comment]
I can't reproduce this issue. Did you replace any template? The `form_avatar` template for example?

**Comment by cgpro** [comment]
Nope, all default.

**Comment by Toflar** [comment]
Reason was a custom template.
