### ISSUE TITLE
No avatar image is saved

### ISSUE THREAD

**Issue by niebuhrhood** [terminal42/contao-avatar#5]
Hi there,

no avatar image will be saved in Member Reg form.
Only when editing member data with "Persönliche Daten".

Contao 3.5 Composer
contao-avatar dev-develop
(1.0.2 ist not working, no avatar upload will show up in FE and no checkbox in BE)

My log is also empty, no error message...

THnks in advance for feedback!

**Comment by qzminski** [comment]
The avatar field is not yet supported in the registration module.

**Comment by niebuhrhood** [comment]
In version 1.2.1 its now working in the registration module with Contao 3.5.4

**Comment by qzminski** [comment]
Oh really? Cool then 😄
