### ISSUE TITLE
Incompatibility with contao-fineuploader

### ISSUE THREAD

**Issue by malitze** [terminal42/contao-avatar#6]
Hi there,

when using both contao-avatar and contao-fineuploader on the same page (in my case in the member personal data form) this seems to cause conflict leaving the fineuploader not working. Each extension for itself is working fine. 

Can you think of a solution? Maybe I could make the avatar extension aware of the fineuploader and have it use that one if present?

Using Contao 3.5.15 Composer with 
terminal42/contao-avatar	1.2.0
terminal42/contao-fineuploader	2.0.0

Thank you so much for both extensions in advance!

**Comment by aschempp** [comment]
Maybe we make `contao-fineuploader` a dependency of `contao-avatar`?

**Comment by qzminski** [comment]
Doubt that, we use cropping feature in combination with FineUploader there.

**Comment by malitze** [comment]
Seems the problem is that the Form* FE widget that gets constructed first does not expect the ajax request to be designated for another receiver and therefor sets `\Input::setGet('no_ajax', 1);`. So the request serves the complete page instead of the designated ajax request.

As a quick fix I changed each extension to set its specific no_ajax flag which seems to work fine as far as I can tell.

**Comment by qzminski** [comment]
Could you try 8c5b75a please?

**Comment by malitze** [comment]
Solved it, thank you very much!
