### ISSUE TITLE
Problems with spaces in filename

### ISSUE THREAD

**Issue by niebuhrhood** [terminal42/contao-avatar#7]
Hi there, 
if you have an image with spaces in filename, then there is no dynamic height value in div.jcrop-holder.
Strange...

Anyone having same issue?

**Comment by qzminski** [comment]
I can't reproduce that. What filename and file have you tried? Can you upload it here so I can test it?

**Comment by qzminski** [comment]
By the way this issue I have discovered a similar bug. Maybe you can also try the fix from 16a1cac.

**Comment by niebuhrhood** [comment]
Sorry, I was on holiday.
Thanks for the fix, I tried.

The calculated inline height is still 0px.
