### ISSUE TITLE
Fatal error: Call to undefined method Avatar::getMemberPath() in ....

### ISSUE THREAD

**Issue by jedoStyle** [terminal42/contao-avatar#8]
nach der installation, lassen sich Members, Users und Settings nicht mehr öffnen, sondern es kommt eine FM (hier mal für Members)

`Fatal error: Call to undefined method Avatar::getMemberPath() in ....`

**Comment by Toflar** [comment]
Diese Klasse ist aber da. Sicher, dass das Modul korrekt installiert wurde (nach `system/modules/avatar`)?

**Comment by jedoStyle** [comment]
ja ist alles korrekt installiert, habe aber heute herausgefunden, das sich diese AvatarClass mit einer anderen nicht verträgt. (con4forum) hat eine eingebaute avatarclasse die genauso heist

**Comment by Toflar** [comment]
Alles klar. Danke für's Feedback.

**Comment by jedoStyle** [comment]
könnt ihr da etwas mache ? das sich das nicht mehr behindert ?

**Comment by Toflar** [comment]
Ja, wir (oder con4forum) könnten die Klasse in einen Namespace schieben. Das wäre aber nicht mehr rückwärtskompatibel und müsste (in unserem Fall, was con4forum macht, müssen sie selber wissen) eine 2.0.0 werden. Jeder der diese Extension irgendwie erweitert und auf die 2.0.0 aktualisiert, müsste seinen Code anpassen. Das werden wir erst mal nicht tun, dafür ist sie bei zu vielen Projekten von uns im Einsatz.

**Comment by jedoStyle** [comment]
okay danke dir für die info
